src/src/BioSounds/Entity/IndexLog.php
<?php

namespace BioSounds\Entity;


use BioSounds\Provider\BaseProvider;

class IndexLog extends BaseProvider
{
    const TABLE_NAME = 'index_log';

    /**
     * @var int
     */
    private $log_id;

    /**
     * @var int
     */
    private $recording_id;

    /**
     * @var int
     */
    private $user_id;

    /**
     * @var int
     */
    private $index_id;

    /**
     * @var string
     */
    private $coordinates;

    /**
     * @var string
     */
    private $value;

    /**
     * @var string
     */
    private $param;

    /**
     * @var string
     */
    private $creation_date;

    /**
     * @return int
     */
    public function getLogId(): int
    {
        return $this->log_id;
    }

    /**
     * @param int $log_id
     * @return IndexLog
     */
    public function setLogId(int $log_id): IndexLog
    {
        $this->log_id = $log_id;
        return $this;
    }

    /**
     * @return int
     */
    public function getRecordingId(): int
    {
        return $this->recording_id;
    }

    /**
     * @param int $recording_id
     * @return IndexLog
     */
    public function setRecordingId(int $recording_id): IndexLog
    {
        $this->recording_id = $recording_id;
        return $this;
    }

    /**
     * @return int
     */
    public function getUserId(): int
    {
        return $this->user_id;
    }

    /**
     * @param int $user_id
     * @return IndexLog
     */
    public function setUserId(int $user_id): IndexLog
    {
        $this->user_id = $user_id;
        return $this;
    }

    /**
     * @return int
     */
    public function getIndexId(): int
    {
        return $this->index_id;
    }

    /**
     * @param int $index_id
     * @return IndexLog
     */
    public function setIndexId(int $index_id): IndexLog
    {
        $this->index_id = $index_id;
        return $this;
    }

    /**
     * @return string
     */
    public function getCoordinates(): string
    {
        return $this->coordinates;
    }

    /**
     * @param string $coordinates
     * @return IndexLog
     */
    public function setCoordinates(string $coordinates): IndexLog
    {
        $this->coordinates = $coordinates;
        return $this;
    }

    /**
     * @return string
     */
    public function getValue(): string
    {
        return $this->value;
    }

    /**
     * @param string $value
     * @return IndexLog
     */
    public function setValue(string $value): IndexLog
    {
        $this->value = $value;
        return $this;
    }

    /**
     * @return string
     */
    public function getParam(): string
    {
        return $this->param;
    }

    /**
     * @param string $param
     * @return IndexLog
     */
    public function setParam(string $param): IndexLog
    {
        $this->param = $param;
        return $this;
    }


    /**
     * @return string
     */
    public function getDate(): string
    {
        return $this->creation_date;
    }

    /**
     * @param string $creation_date
     * @return IndexLog
     */
    public function setDate(string $creation_date): IndexLog
    {
        $this->creation_date = $creation_date;
        return $this;
    }

    /**
     * @return string
     */
    public function getRecordingName(): string
    {
        return $this->recording_name;
    }

    /**
     * @param string $recording_name
     * @return IndexLog
     */
    public function setRecordingName(string $recording_name): IndexLog
    {
        $this->recording_name = $recording_name;
        return $this;
    }

    /**
     * @return string
     */
    public function getUserName(): string
    {
        return $this->user_name;
    }

    /**
     * @param string $user_name
     * @return IndexLog
     */
    public function setUserName(string $user_name): IndexLog
    {
        $this->user_name = $user_name;
        return $this;
    }

    /**
     * @return string
     */
    public function getIndexName(): string
    {
        return $this->index_name;
    }

    /**
     * @param string $index_name
     * @return IndexLog
     */
    public function setIndexName(string $index_name): IndexLog
    {
        $this->index_name = $index_name;
        return $this;
    }

    /**
     * @param array $indexDate
     * @return bool
     * @throws \Exception
     */
    public function insert(array $indexDate): bool
    {
        if (empty($indexDate)) {
            return false;
        }

        $fields = "( ";
        $valuesNames = "( ";
        $values = array();

        foreach ($indexDate as $key => $value) {
            $fields .= $key;
            $valuesNames .= ":" . $key;
            $values[":" . $key] = $value;
            if (end($indexDate) !== $value) {
                $fields .= ", ";
                $valuesNames .= ", ";
            }
        }
        $fields .= " )";
        $valuesNames .= " )";
        $this->database->prepareQuery("INSERT INTO index_log $fields VALUES $valuesNames");
        return $this->database->executeInsert($values);
    }
}

src/src/BioSounds/Controller/Administration/RecordingController.php
<?php

namespace BioSounds\Controller\Administration;

use BioSounds\Controller\BaseController;
use BioSounds\Entity\License;
use BioSounds\Entity\Recording;
use BioSounds\Entity\Sensor;
use BioSounds\Exception\ForbiddenException;
use BioSounds\Provider\CollectionProvider;
use BioSounds\Provider\RecordingProvider;
use BioSounds\Provider\SpectrogramProvider;
use BioSounds\Provider\SiteProvider;
use BioSounds\Provider\SoundProvider;
use BioSounds\Provider\SoundTypeProvider;
use BioSounds\Utils\Auth;

class RecordingController extends BaseController
{
    const SECTION_TITLE = 'Recordings';

    /**
     * @param int|null $cId
     * @param int $page
     * @return mixed
     * @throws \Exception
     */
    public function show(int $cId = null, int $page = 1)
    {
        if (!Auth::isUserAdmin()) {
            throw new ForbiddenException();
        }

        // colId proceesing
        if (isset($_POST['colId'])) {
            $colId = filter_var($_POST['colId'], FILTER_SANITIZE_STRING);
        }
        if (!empty($cId)) {
            $colId = $cId;
        }

        $collections = (new CollectionProvider())->getList();
        if (empty($colId)) {
            $colId = $collections[0]->getId();
        }

        $recordingProvider = new RecordingProvider();

        $recordings = $recordingProvider->getListByCollection(
            $colId,
            (Auth::getUserID() == null) ? 0 : Auth::getUserID(),
            $this::ITEMS_PAGE,
            $this::ITEMS_PAGE * ($page - 1)
        );

        $userSites = (new SiteProvider())->getBasicList();

        $siteFieldFlags = [];
        foreach ($recordings as $rec) {
            $siteFieldFlags[$rec->getId()] = 0;
            foreach ($userSites as $st) {
                if ($st->getId() == $rec->getSite()) {
                    $siteFieldFlags[$rec->getId()] = 1;
                }
            }
        }

        $recordingNum = $recordingProvider->countAllByCollection($colId);
        $pages = $recordingNum > 0 ? ceil($recordingNum / self::ITEMS_PAGE) : 1;

        return $this->twig->render('administration/recordings.html.twig', [
            'colId' => $colId,
            'recordings' => $recordings,
            'sites' => $userSites,
            'siteFieldFlags' => $siteFieldFlags,
            'sensors' => (new Sensor())->getBasicList(),
            'soundTypes' => (new SoundTypeProvider())->getList(),
            'license' => (new License())->getBasicList(),
            'currentPage' => ($page > $pages) ?: $page,
            'pages' => $pages
        ]);
    }

    /**
     * @return bool|int|null
     * @throws \Exception
     */
    public function save()
    {
        if (!Auth::isUserAdmin()) {
            throw new ForbiddenException();
        }

        $data = [];
        foreach ($_POST as $key => $value) {
            if (strpos($key, "_")) {
                $type = substr($key, strripos($key, "_") + 1, strlen($key));
                $key = substr($key, 0, strripos($key, "_"));
                switch ($type) {
                    case "date":
                        $data[$key] =  filter_var($value, FILTER_SANITIZE_STRING);
                        break;
                    case "time":
                        $data[$key] =  filter_var($value, FILTER_SANITIZE_STRING);
                        break;
                    case "text":
                        $data[$key] =  filter_var($value, FILTER_SANITIZE_STRING);
                        break;
                    case 'select-one':
                        $data[$key] =  filter_var($value, FILTER_SANITIZE_NUMBER_INT);
                        break;
                    case "hidden":
                        $data[$key] =  filter_var($value, FILTER_SANITIZE_NUMBER_INT);
                        break;
                }
            } else
                $data[$key] =  filter_var($value, FILTER_SANITIZE_STRING);
        }

        if (isset($data["itemID"])) {
            (new RecordingProvider())->update($data);

            return json_encode([
                'errorCode' => 0,
                'message' => 'Recording updated successfully.',
            ]);
        }
    }

    /**
     * @param int $id
     * @return false|string
     * @throws \Exception
     */
    public function delete(int $id)
    {
        if (!Auth::isUserAdmin()) {
            throw new ForbiddenException();
        }

        if (empty($id)) {
            throw new \Exception(ERROR_EMPTY_ID);
        }

        $recordingProvider = new RecordingProvider();
        $recording = $recordingProvider->get($id);

        $fileName = $recording[Recording::FILENAME];
        $colId = $recording[Recording::COL_ID];
        $dirID = $recording[Recording::DIRECTORY];

        $soundsDir = "sounds/sounds/$colId/$dirID/";
        $imagesDir = "sounds/images/$colId/$dirID/";

        unlink($soundsDir . $fileName);
        //Check if there are images
        $images = (new SpectrogramProvider())->getListInRecording($id);

        foreach ($images as $image) {
            unlink($imagesDir . $image->getFilename());
        }

        $wavFileName = substr($fileName, 0, strrpos($fileName, '.')) . '.wav';
        if (is_file($soundsDir . $wavFileName)) {
            unlink($soundsDir . $wavFileName);
        }

        $recordingProvider->delete($id);

        if (!empty($recording[Recording::SOUND_ID])) {
            (new SoundProvider())->delete($recording[Recording::SOUND_ID]);
        }

        return json_encode([
            'errorCode' => 0,
            'message' => 'Recording deleted successfully.',
        ]);
    }
}

src/templates/recording/player/frequencyScale.html.twig
<div class="col-auto ml-auto" style="background:transparent; margin-top:7px;">
    <table class="table-responsive" cellpadding="0"  border="0">
        <tr class="align-top" height="{{ frequency_data.freqMaxHeight }}">
            <td>
                <small>{{ frequency_data.freqMax }} Hz</small>
            </td>
        </tr>
        <tr><td>&nbsp;</td></tr>
        <tr class="align-bottom" height="{{ frequency_data.freqMid2Height }}">
            <td>
                <small>{{ frequency_data.freqMid2 }} Hz</small>
            </td>
        </tr>
        <tr class="align-bottom" height="{{ frequency_data.freqMid1Height }}">
            <td>
                <small>{{ frequency_data.freqMid1 }} Hz</small>
            </td>
        </tr>
        <tr class="align-bottom" height="{{ frequency_data.freqMinHeight }}">
            <td>
                <small>{{ frequency_data.freqMin }} Hz</small>
            </td>
        </tr>
    </table>
</div>

src/templates/recording/player/maadLabel.html.twig
<div>
    <label class="col-form-label form-inline">
        <div>Description:</div>
        <a class="maad-laber" href="{{ index.URL }}">{{ index.description }}</a>
    </label>
</div>
{% if index.param is not null and index.param != '' %}
    {% for p in index.param|split('!') %}
        <div class="form-group form-inline">
            <input id="{{ p }}" name="{{ p }}" class="form-control form-control-sm" size="4" type="text">
            <label class="ml-2 col-form-label-sm" for="{{ p }}">{{ p }}</label>
        </div>
    {% endfor %}
{% endif %}
<a href="{{ baseUrl }}/recording/maad" class="js-maad-modal btn btn-outline-primary">Submit</a>
<script>
    $(".js-maad-modal").click(function (e) {
        let data = []
        let param = ''
        {% if index.param is not null and index.param != '' %}
        {% for p in index.param|split('!') %}
        if ($('#{{ p }}').val() != '') {
            param = param + '{{ p }}' + '?' + $('#{{ p }}').val() + '@'
        }
        {% endfor %}
        {% endif %}
        data = {
            'minTime': $('input[name=minTimeView]').val(),
            'maxTime': $('input[name=maxTimeView]').val(),
            'minFrequency': $('input[name=minFreqView]').val(),
            'maxFrequency': $('input[name=maxFreqView]').val(),
            'collection_id': $('input[name=collection_id]').val(),
            'recording_id': $('input[name=recording_id]').val(),
            'recording_name': $('input[name=recording_name]').val(),
            'recording_directory': $('input[name=recording_directory]').val(),
            'index_id': $('#maad').val(),
            'index': $('#maad').find("option:selected").text(),
            'channel_num': $('input[name=channel_num]').val(),
            'channel': $('input[name=channel]').val(),
            'param': param,
        };
        requestModal(this.href, data, true);
        e.preventDefault();
    });
</script>

src/templates/recording/player/maadResult.html.twig
<div class="modal fade" id="modal-div" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">{{ title }}</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            {% if result!='' %}
                <div class="modal-body ml-3">
                    <form id="maadResultForm">
                        {% for r in result|split('!') %}
                            <div class="form-group" id="cust_label_group">
                                <label for="cust_label">{{ r|split('?')[0] }}
                                    : {{ r|split('?')[1]|number_format(2,'.',',') }}</label>
                            </div>
                        {% endfor %}
                        <input type="hidden" name="recording_id" value="{{ recording_id }}">
                        <input type="hidden" name="index_id" value="{{ index_id }}">
                        <input type="hidden" name="coordinates" value="{{ coordinates }}">
                        <input type="hidden" name="value" value="{{ result }}">
                        <input type="hidden" name="param" value="{{ param }}">
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-outline-secondary" data-dismiss="modal" aria-label="Close">
                        <i class="fas fa-times"></i>
                        Close
                    </button>
                    <button id="maadResultButton" type="submit" class="btn btn-outline-primary">
                        <i class="fas fa-save"></i>
                        Save
                    </button>
                </div>
            {% endif %}
        </div>
    </div>
</div>

src/templates/recording/player/newLabel.html.twig
<div class="modal fade" id="modal-div" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Custom label</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form id="newLabelForm">
                    <div class="form-group" id="cust_label_group">
                        <label for="cust_label">New Label (Up to 20 characters )</label>
                        <input id="cust_label" name="cust_label" class="form-control" type="text" maxlength="20" title="Up to 20 characters allowed" required>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button id="newLabelButton" type="submit" class="btn btn-outline-primary">
                    <i class="fas fa-save"></i>
                    Save</button>
            </div>
        </div>
    </div>
</div>

src/templates/recording/player/player.html.twig
<div class="row">
    <div class="col-6-auto">
        <div id="myCanvas" class="canvas">
            {% if isUserLogged %}
                {% include 'recording/player/tagBoxes.html.twig' with {'tags': player.tags, 'show_tags': player.isShowTags} %}
            {% endif %}
            <div id="playerCursor" class="player-line"></div>
            <img src="{{ player.imageFilePath }}" id="cropbox"/>
        </div>

        <div class="row no-gutters mt-1">
            <div class="col-auto mr-auto">
                <div>
                    <button id="play" class="btn btn-link" data-playing="false" role="switch" aria-checked="false"
                            disabled>
                        <i class="fas fa-play"></i>
                    </button>
                    <button id="stop" class="btn btn-link">
                        <i class="fas fa-stop"></i>
                    </button>
                    <h8>
                        <span id="time_sec_div">{{ player.minTime > 0 ? player.minTime|round: 0 }}</span>
                        /
                        <span id="duration">{{ (player.maxTime - player.minTime|round) }}
                            s</span>
                    </h8>
                </div>
            </div>
            <div class="col-auto">
                <form class="form-inline" id="recordingForm"
                      action="{{ baseUrl }}/recording/show/{{ player.recording.recording_id }}" method="post">
                    <input type="hidden" name="channel" value="{{ player.channel }}">
                    <input type="hidden" name="channel_num" value="{{ player.recording.channel_num }}">
                    <input type='hidden' name='showTags' value="{{ player.showTags }}">
                    <input type='hidden' name='estimateDistID' value="{{ player.estimateDistID }}">
                    <input type="hidden" name="collection_id" value="{{ player.recording.col_id }}">
                    <input type="hidden" name="recording_id" value="{{ player.recording.recording_id }}">
                    <input type="hidden" name="recording_name" value="{{ player.recording.name }}">
                    <input type="hidden" name="recording_directory" value="{{ player.recording.directory }}">
                    <input type="hidden" name="specWidth" value="{{ player.spectrogramWidth }}">
                    <input type="hidden" name="specHeight" value="{{ player.spectrogramHeight }}">
                    <input type="hidden" name="minTimeView" value="{{ player.minTime }}">
                    <input type="hidden" name="maxTimeView" value="{{ player.maxTime }}">
                    <input type="hidden" name="minFreqView" value="{{ player.minFrequency }}">
                    <input type="hidden" name="maxFreqView" value="{{ player.maxFrequency }}">

                    {% include 'recording/player/timeBoxes.html.twig' with {
                        'minTime': player.minTime,
                        'maxTime': player.maxTime,
                        'minFrequency': player.minFrequency,
                        'maxFrequency': player.maxFrequency,
                    } only %}

                    <div class="btn-group dark-buttons" role="group">
                        <a href="#" id="exportCoordinates" class="btn btn-link" title="Export coordinates to clipboard">
                            <i class="fas fa-clipboard"></i>
                        </a>
                        <button id="zoom-submit" class="btn btn-link" type="button" title="Zoom" disabled>
                            <i class="fas fa-search-plus"></i>
                        </button>
                    </div>
                    <div class="btn-group btn-group-toggle dark-buttons" data-toggle="buttons">
                        <label for="continuous-play" class="btn btn-link {{ player.isContinuousPlay ? 'active':'' }}"
                               title="Continuous playback">
                            <input type="checkbox" id="continuous-play" name="continuous_play"
                                   autocomplete="off" {{ player.isContinuousPlay ? 'checked':'' }}>
                            <i class="fas fa-redo-alt"></i>
                        </label>
                        <label for="filter" class="btn btn-link" title="Filter">
                            <input type="checkbox" id="filter" name="filter">
                            <i class="fas fa-filter"></i>
                        </label>
                    </div>
                </form>
            </div>
        </div>
    </div>
    {% if isUserLogged %}
        <div class="col-auto">
            <div>
                <label class="col-form-label">
                    <strong>My Label:</strong>
                </label>
            </div>
            <div>
                <form id="reclabelform" novalidate>
                    <input type="hidden" name="recording_id" value="{{ player.recording.recording_id }}"/>
                    <input type="hidden" name="user_id" value="{{ user_id }}"/>
                    <select id="reclabel" name="label_id" required>
                        {% for lbl in labels %}
                            <option value="{{ lbl.id }}" {{ lbl.id == myLabel.id ? 'selected' }}>{{ lbl.name }}</option>
                        {% endfor %}
                    </select>
                    <a href="{{ baseUrl }}/recording/addLabel" class="js-open-modal" title="add custom label">
                        <i class="fas fa-plus pr-1"></i>
                    </a>
                </form>

            </div>
            <div>
                <label class="col-form-label">
                    <strong>Acoustic Index Analysis:</strong>
                </label>
            </div>
            <div>
                <select id="maad" name="maad_id" autocomplete="off" required>
                    {% for index in indexs %}
                        <option value="{{ index.indexId }}">{{ index.name }}</option>
                    {% endfor %}
                </select>
                <div>
                    <label class="col-form-label form-inline">
                        <div>Description:</div>
                        <a class="maad-laber" href="{{ indexs[0].URL }}">{{ indexs[0].description }}</a>
                    </label>
                </div>
                {% if indexs[0].param is not null and indexs[0].param != '' %}
                    {% for p in indexs[0].param|split('!') %}
                        <div class="form-group form-inline">
                            <input id="{{ p }}" name="{{ p }}" class="form-control form-control-sm" size="4"
                                   type="text">
                            <label class="ml-2 col-form-label-sm" for="{{ p }}">{{ p }}</label>
                        </div>
                    {% endfor %}
                {% endif %}
                <a href="{{ baseUrl }}/recording/maad" class="js-maad-modal btn btn-outline-primary">Submit</a>
                <script>
                    $(".js-maad-modal").click(function (e) {
                        let data = []
                        let param = ''
                        {% if indexs[0].param is not null and indexs[0].param != '' %}
                        {% for p in indexs[0].param|split('!') %}
                        param = param + p + '?' + $('.{{ p }}').val() + '@'
                        {% endfor %}
                        {% endif %}
                        data = {
                            'minTime': $('input[name=minTimeView]').val(),
                            'maxTime': $('input[name=maxTimeView]').val(),
                            'minFrequency': $('input[name=minFreqView]').val(),
                            'maxFrequency': $('input[name=maxFreqView]').val(),
                            'collection_id': $('input[name=collection_id]').val(),
                            'recording_id': $('input[name=recording_id]').val(),
                            'recording_name': $('input[name=recording_name]').val(),
                            'recording_directory': $('input[name=recording_directory]').val(),
                            'index_id': $('#maad').val(),
                            'index': $('#maad').find("option:selected").text(),
                            'channel_num': $('input[name=channel_num]').val(),
                            'channel': $('input[name=channel]').val(),
                            'param': param,
                        };
                        requestModal(this.href, data, true);
                        e.preventDefault();
                    });
                </script>
            </div>
        </div>
        <script>
            $("#maad").change(function () {
                {% for index in indexs %}
                if ($("#maad").val() =={{ index.indexId }}) {
                    $(".maad-laber").attr('href', "{{ index.URL }}")
                    $(".maad-laber").text("{{ index.description }}")
                    $.ajax({
                        url: "{{ baseUrl }}/recording/getMaadlabel/" + {{ index.indexId }},
                        success: function (data) {
                            $("#maad").nextAll().remove()
                            if (data) {
                                $("#maad").after(data)
                            }
                        },
                    })
                }
                {% endfor %}
            })
        </script>
    {% endif %}
    {#    {% include 'recording/player/frequencyScale.html.twig' %} #}
</div>

src/templates/recording/player/tagBoxes.html.twig
{% for tag in tags %}
    <div class="tag-controls {{ tag.style }}" id="{{ tag.id }}"
         style="z-index: {{ tag.position }}; border-color: {{ tag.color }}; left: {{ tag.left }}px; top: {{ tag.top }}px; height: {{ tag.height }}px; width: {{ tag.width }}px; {{ show_tags ? '' : 'display:none;' }}"></div>

    <div class="card js-panel-tag" style="display:none;">
        <div class="card-header">
            <small>{{ tag.id }} | {{ tag.title }}</small>
        </div>
        <div class="card-body mx-auto">
            <div class="btn-group" role="group">
                <a href="{{ baseUrl }}/api/tag/edit/{{ tag.id }}" class='btn btn-outline-primary btn-sm js-tag'
                   title='Edit tag'>
                    <i class='fas fa-edit' aria-hidden='true'></i>
                </a>

                <a href='#' onclick='return false;' class='btn btn-outline-primary btn-sm zoom-tag' title='Zoom tag'>
                    <i class='fas fa-search' aria-hidden='true'></i>
                </a>
                <a href='#' onclick='return false;' id="est_{{ tag.id }}" type='button'
                   class='btn btn-outline-primary btn-sm estimate-distance' title='Estimate call distance'>
                    <i class='fas fa-bullhorn' aria-hidden='true'></i>
                </a>
            </div>
        </div>
    </div>
{% endfor %}

src/templates/recording/player/timeBoxes.html.twig
<div class="form-group mr-2">
    <label class="col-form-label-sm mr-2" for="x">Time:</label>
    <input type="text" class="form-control form-control-sm" id="x" name="t_min" size="5" value="{{ minTime }}" title="Minimum time">
</div>
<div class="form-group mr-2">
    <label class="col-form-label-sm mr-2" for="w">to</label>
    <input type="text" class="form-control form-control-sm" id="w" name="t_max" size="5" value="{{ maxTime }}" title="Maximum time">
    <label class="col-form-label-sm mr-2" for="w">s</label>
</div>
<div class="form-group mr-2">
    <label class="col-form-label-sm mr-2" for="y">Frequency:</label>
    <input type="text" class="form-control form-control-sm" id="y" name="f_min" size="4" value="{{ minFrequency }}" title="Minimum frequency">
</div>
<div class="form-group">
    <label class="col-form-label-sm mr-2" for="h">to</label>
    <input type="text" class="form-control form-control-sm" id="h" name="f_max" size="4" value="{{ maxFrequency }}" title="Maximum frequency">
    <label class="col-form-label-sm mr-2" for="h">Hz</label>
</div>