src/src/BioSounds/Entity/IndexLog.php
<?php

namespace BioSounds\Entity;


use BioSounds\Provider\BaseProvider;

class IndexLog extends BaseProvider
{
    const TABLE_NAME = 'index_log';

    /**
     * @var int
     */
    private $log_id;

    /**
     * @var int
     */
    private $recording_id;

    /**
     * @var int
     */
    private $user_id;

    /**
     * @var int
     */
    private $index_id;

    /**
     * @var string
     */
    private $coordinates;

    /**
     * @var string
     */
    private $value;

    /**
     * @var string
     */
    private $param;

    /**
     * @var string
     */
    private $creation_date;

    /**
     * @return int
     */
    public function getLogId(): int
    {
        return $this->log_id;
    }

    /**
     * @param int $log_id
     * @return IndexLog
     */
    public function setLogId(int $log_id): IndexLog
    {
        $this->log_id = $log_id;
        return $this;
    }

    /**
     * @return int
     */
    public function getRecordingId(): int
    {
        return $this->recording_id;
    }

    /**
     * @param int $recording_id
     * @return IndexLog
     */
    public function setRecordingId(int $recording_id): IndexLog
    {
        $this->recording_id = $recording_id;
        return $this;
    }

    /**
     * @return int
     */
    public function getUserId(): int
    {
        return $this->user_id;
    }

    /**
     * @param int $user_id
     * @return IndexLog
     */
    public function setUserId(int $user_id): IndexLog
    {
        $this->user_id = $user_id;
        return $this;
    }

    /**
     * @return int
     */
    public function getIndexId(): int
    {
        return $this->index_id;
    }

    /**
     * @param int $index_id
     * @return IndexLog
     */
    public function setIndexId(int $index_id): IndexLog
    {
        $this->index_id = $index_id;
        return $this;
    }

    /**
     * @return string
     */
    public function getCoordinates(): string
    {
        return $this->coordinates;
    }

    /**
     * @param string $coordinates
     * @return IndexLog
     */
    public function setCoordinates(string $coordinates): IndexLog
    {
        $this->coordinates = $coordinates;
        return $this;
    }

    /**
     * @return string
     */
    public function getValue(): string
    {
        return $this->value;
    }

    /**
     * @param string $value
     * @return IndexLog
     */
    public function setValue(string $value): IndexLog
    {
        $this->value = $value;
        return $this;
    }

    /**
     * @return string
     */
    public function getParam(): string
    {
        return $this->param;
    }

    /**
     * @param string $param
     * @return IndexLog
     */
    public function setParam(string $param): IndexLog
    {
        $this->param = $param;
        return $this;
    }


    /**
     * @return string
     */
    public function getDate(): string
    {
        return $this->creation_date;
    }

    /**
     * @param string $creation_date
     * @return IndexLog
     */
    public function setDate(string $creation_date): IndexLog
    {
        $this->creation_date = $creation_date;
        return $this;
    }

    /**
     * @return string
     */
    public function getRecordingName(): string
    {
        return $this->recording_name;
    }

    /**
     * @param string $recording_name
     * @return IndexLog
     */
    public function setRecordingName(string $recording_name): IndexLog
    {
        $this->recording_name = $recording_name;
        return $this;
    }

    /**
     * @return string
     */
    public function getUserName(): string
    {
        return $this->user_name;
    }

    /**
     * @param string $user_name
     * @return IndexLog
     */
    public function setUserName(string $user_name): IndexLog
    {
        $this->user_name = $user_name;
        return $this;
    }

    /**
     * @return string
     */
    public function getIndexName(): string
    {
        return $this->index_name;
    }

    /**
     * @param string $index_name
     * @return IndexLog
     */
    public function setIndexName(string $index_name): IndexLog
    {
        $this->index_name = $index_name;
        return $this;
    }

    /**
     * @param array $indexDate
     * @return bool
     * @throws \Exception
     */
    public function insert(array $indexDate): bool
    {
        if (empty($indexDate)) {
            return false;
        }

        $fields = "( ";
        $valuesNames = "( ";
        $values = array();

        foreach ($indexDate as $key => $value) {
            $fields .= $key;
            $valuesNames .= ":" . $key;
            $values[":" . $key] = $value;
            if (end($indexDate) !== $value) {
                $fields .= ", ";
                $valuesNames .= ", ";
            }
        }
        $fields .= " )";
        $valuesNames .= " )";
        $this->database->prepareQuery("INSERT INTO index_log $fields VALUES $valuesNames");
        return $this->database->executeInsert($values);
    }
}

src/src/BioSounds/Controller/Administration/CollectionController.php
<?php

namespace BioSounds\Controller\Administration;

use BioSounds\Controller\BaseController;
use BioSounds\Entity\Collection;
use BioSounds\Exception\ForbiddenException;
use BioSounds\Provider\CollectionProvider;
use BioSounds\Utils\Auth;

class CollectionController extends BaseController
{
    const SECTION_TITLE = 'Collections';

    /**
     * @return string
     * @throws \Exception
     */
    public function show(int $page = 1)
    {
        if (!Auth::isUserAdmin()) {
            throw new ForbiddenException();
        }

        $collProvider = new CollectionProvider();

        $collNum = $collProvider->countCollections();
        $pages = $collNum > 0 ? ceil($collNum / self::ITEMS_PAGE) : 1;

        return $this->twig->render('administration/collections.html.twig', [
            'collections' => $collProvider->getCollectionPages(
                $this::ITEMS_PAGE,
                $this::ITEMS_PAGE * ($page - 1)
            ),
            // 'collections' => (new (CollectionProvider))->getList("name"),
            'currentPage' => ($page > $pages) ?: $page,
            'pages' => $pages
        ]);
    }


    /**
     * @return false|string
     * @throws \Exception
     */
    public function save()
    {
        $collProvider = new Collection();

        if (!Auth::isUserAdmin()) {
            throw new ForbiddenException();
        }

        $data = [];

        foreach ($_POST as $key => $value) {
            if (strrpos($key, '_')) {
                $type = substr($key, strrpos($key, '_') + 1, strlen($key));
                $key = substr($key, 0, strrpos($key, '_'));
            }
            $data[$key] = filter_var($value, FILTER_SANITIZE_STRING);
        }
        $data['user_id']=$_SESSION['user_id'];
        if (isset($data['collId'])) {
            $collProvider->updateColl($data);
            return json_encode([
                'errorCode' => 0,
                'message' => 'Collection updated successfully.'
            ]);
        } else if ($collProvider->insertColl($data) > 0) {
            return json_encode([
                'errorCode' => 0,
                'message' => 'Collection created successfully.',
            ]);
        }
    }

    /**
     * @return false|string
     * @throws \Exception
     */
    public function editCollection()
    {
        if (!Auth::isUserAdmin()) {
            throw new ForbiddenException();
        }

        $collId = filter_var($_POST['id'], FILTER_SANITIZE_NUMBER_INT);
        return json_encode([
            'errorCode' => 0,
            'data' => $this->twig->render('administration/collEdit.html.twig', [
                'collId' => $collId,
            ]),
        ]);
    }

    /**
     * @throws \Exception
     */
    public function export()
    {
        if (!Auth::isUserAdmin()) {
            throw new ForbiddenException();
        }

        $file_name = "collections.csv";
        $fp = fopen('php://output', 'w');
        header('Content-Type: application/octet-stream;charset=utf-8');
        header('Accept-Ranges:bytes');
        header('Content-Disposition: attachment; filename=' . $file_name);

        $collList = (new CollectionProvider())->getList();

        foreach ($collList as $collItem) {
            $colArray = array($collItem->getId(), $collItem->getName(), $collItem->getAuthor(), $collItem->getDoi(), $collItem->getNote(), $collItem->getProject());
            $colAls[] = $colArray;
        }

        foreach ($colAls as $line) {
            fputcsv($fp, $line);
        }
        fclose($fp);
        exit();
    }
}

src/src/BioSounds/Controller/Administration/IndexLogController.php
<?php

namespace BioSounds\Controller\Administration;

use BioSounds\Controller\BaseController;
use BioSounds\Exception\ForbiddenException;
use BioSounds\Provider\IndexLogProvider;
use BioSounds\Utils\Auth;

class IndexLogController extends BaseController
{
    const SECTION_TITLE = 'IndexLogs';

    /**
     * @return string
     * @throws \Exception
     */
    public function show(int $page = 1)
    {
        if (!Auth::isUserLogged()) {
            throw new ForbiddenException();
        }
        $indexLogProvider = new IndexLogProvider();
        $indexLogNum = $indexLogProvider->countIndexLogs();
        $pages = $indexLogNum > 0 ? ceil($indexLogNum / self::ITEMS_PAGE) : 1;
        return $this->twig->render('administration/indexLogs.html.twig', [
            'indexLogs' => $indexLogProvider->getIndexLogPages(
                $this::ITEMS_PAGE,
                $this::ITEMS_PAGE * ($page - 1)
            ),
            'currentPage' => ($page > $pages) ?: $page,
            'pages' => $pages
        ]);
    }

    /**
     * @throws \Exception
     */
    public function export()
    {
        if (!Auth::isUserLogged()) {
            throw new ForbiddenException();
        }

        $file_name = "indexLogs.csv";
        $fp = fopen('php://output', 'w');
        header('Content-Type: application/octet-stream;charset=utf-8');
        header('Accept-Ranges:bytes');
        header('Content-Disposition: attachment; filename=' . $file_name);

        $indexLogList = (new IndexLogProvider())->getList();
        $indexLogAls[] = array('#', 'Recording', 'Creation User', 'Index', 'Coordinates', 'Parameter', 'Result', 'Creation Date (UTC)');

        foreach ($indexLogList as $indexLogItem) {
            $value = '';
            foreach (explode('!', $indexLogItem->getValue()) as $v) {
                $value = $value . explode('?', $v)[0] . ': ' . number_format(explode('?', $v)[1], 2, '.', ',') . '; ';
            }
            $indexLogArray = array(
                $indexLogItem->getLogId(),
                $indexLogItem->getRecordingName(),
                $indexLogItem->getUserName(),
                $indexLogItem->getIndexName(),
                $indexLogItem->getCoordinates(),
                str_replace('@', '; ', str_replace('?', ': ', $indexLogItem->getParam())),
                $value,
                $indexLogItem->getDate(),
            );
            $indexLogAls[] = $indexLogArray;
        }

        foreach ($indexLogAls as $line) {
            fputcsv($fp, $line);
        }
        fclose($fp);
        exit();
    }
}

src/src/BioSounds/Controller/Administration/RecordingController.php
<?php

namespace BioSounds\Controller\Administration;

use BioSounds\Controller\BaseController;
use BioSounds\Entity\License;
use BioSounds\Entity\Recording;
use BioSounds\Entity\Sensor;
use BioSounds\Exception\ForbiddenException;
use BioSounds\Provider\CollectionProvider;
use BioSounds\Provider\RecordingProvider;
use BioSounds\Provider\SpectrogramProvider;
use BioSounds\Provider\SiteProvider;
use BioSounds\Provider\SoundProvider;
use BioSounds\Provider\SoundTypeProvider;
use BioSounds\Utils\Auth;

class RecordingController extends BaseController
{
    const SECTION_TITLE = 'Recordings';

    /**
     * @param int|null $cId
     * @param int $page
     * @return mixed
     * @throws \Exception
     */
    public function show(int $cId = null, int $page = 1)
    {
        if (!Auth::isUserAdmin()) {
            throw new ForbiddenException();
        }

        // colId proceesing
        if (isset($_POST['colId'])) {
            $colId = filter_var($_POST['colId'], FILTER_SANITIZE_STRING);
        }
        if (!empty($cId)) {
            $colId = $cId;
        }

        $collections = (new CollectionProvider())->getList();
        if (empty($colId)) {
            $colId = $collections[0]->getId();
        }

        $recordingProvider = new RecordingProvider();

        $recordings = $recordingProvider->getListByCollection(
            $colId,
            (Auth::getUserID() == null) ? 0 : Auth::getUserID(),
            $this::ITEMS_PAGE,
            $this::ITEMS_PAGE * ($page - 1)
        );

        $userSites = (new SiteProvider())->getBasicList();

        $siteFieldFlags = [];
        foreach ($recordings as $rec) {
            $siteFieldFlags[$rec->getId()] = 0;
            foreach ($userSites as $st) {
                if ($st->getId() == $rec->getSite()) {
                    $siteFieldFlags[$rec->getId()] = 1;
                }
            }
        }

        $recordingNum = $recordingProvider->countAllByCollection($colId);
        $pages = $recordingNum > 0 ? ceil($recordingNum / self::ITEMS_PAGE) : 1;

        return $this->twig->render('administration/recordings.html.twig', [
            'colId' => $colId,
            'recordings' => $recordings,
            'sites' => $userSites,
            'siteFieldFlags' => $siteFieldFlags,
            'sensors' => (new Sensor())->getBasicList(),
            'soundTypes' => (new SoundTypeProvider())->getList(),
            'license' => (new License())->getBasicList(),
            'currentPage' => ($page > $pages) ?: $page,
            'pages' => $pages
        ]);
    }

    /**
     * @return bool|int|null
     * @throws \Exception
     */
    public function save()
    {
        if (!Auth::isUserAdmin()) {
            throw new ForbiddenException();
        }

        $data = [];
        foreach ($_POST as $key => $value) {
            if (strpos($key, "_")) {
                $type = substr($key, strripos($key, "_") + 1, strlen($key));
                $key = substr($key, 0, strripos($key, "_"));
                switch ($type) {
                    case "date":
                        $data[$key] =  filter_var($value, FILTER_SANITIZE_STRING);
                        break;
                    case "time":
                        $data[$key] =  filter_var($value, FILTER_SANITIZE_STRING);
                        break;
                    case "text":
                        $data[$key] =  filter_var($value, FILTER_SANITIZE_STRING);
                        break;
                    case 'select-one':
                        $data[$key] =  filter_var($value, FILTER_SANITIZE_NUMBER_INT);
                        break;
                    case "hidden":
                        $data[$key] =  filter_var($value, FILTER_SANITIZE_NUMBER_INT);
                        break;
                }
            } else
                $data[$key] =  filter_var($value, FILTER_SANITIZE_STRING);
        }

        if (isset($data["itemID"])) {
            (new RecordingProvider())->update($data);

            return json_encode([
                'errorCode' => 0,
                'message' => 'Recording updated successfully.',
            ]);
        }
    }

    /**
     * @param int $id
     * @return false|string
     * @throws \Exception
     */
    public function delete(int $id)
    {
        if (!Auth::isUserAdmin()) {
            throw new ForbiddenException();
        }

        if (empty($id)) {
            throw new \Exception(ERROR_EMPTY_ID);
        }

        $recordingProvider = new RecordingProvider();
        $recording = $recordingProvider->get($id);

        $fileName = $recording[Recording::FILENAME];
        $colId = $recording[Recording::COL_ID];
        $dirID = $recording[Recording::DIRECTORY];

        $soundsDir = "sounds/sounds/$colId/$dirID/";
        $imagesDir = "sounds/images/$colId/$dirID/";

        unlink($soundsDir . $fileName);
        //Check if there are images
        $images = (new SpectrogramProvider())->getListInRecording($id);

        foreach ($images as $image) {
            unlink($imagesDir . $image->getFilename());
        }

        $wavFileName = substr($fileName, 0, strrpos($fileName, '.')) . '.wav';
        if (is_file($soundsDir . $wavFileName)) {
            unlink($soundsDir . $wavFileName);
        }

        $recordingProvider->delete($id);

        if (!empty($recording[Recording::SOUND_ID])) {
            (new SoundProvider())->delete($recording[Recording::SOUND_ID]);
        }

        return json_encode([
            'errorCode' => 0,
            'message' => 'Recording deleted successfully.',
        ]);
    }
}

src/templates/administration/admin.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="container">
        <nav aria-label="breadcrumb">
            <ul class="breadcrumb bg-white mt-4">
                <li class="breadcrumb-item" aria-current="page">
                    <a href="{{ baseUrl }}/admin/settings">Administration</a>
                </li>
                <li class="breadcrumb-item active" aria-current="page">{{ section }}</li>
            </ul>
        </nav>

        <div class="row">
            <div class="col-lg-2">
                <ul class="nav flex-column nav-pills">
                    {% if is_admin %}
                        <li class="nav-item">
                            <a class="nav-link" href="{{ baseUrl }}/admin/settings">
                                <i class="fas fa-cog pr-1"></i>
                                Settings</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ baseUrl }}/admin/collections">
                                <i class="fas fa-music pr-1"></i>
                                Collections</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ baseUrl }}/admin/users">
                                <i class="fas fa-user pr-1"></i>
                                Users</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ baseUrl }}/admin/recordings">
                                <i class="fas fa-compact-disc pr-1"></i>
                                Recordings</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ baseUrl }}/admin/sites">
                                <i class="fa fa-sites pr-1"></i>
                                Sites</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{{ baseUrl }}/admin/selfService">
                                <i class="fas fa-user pr-1"></i>
                                User</a>
                        </li>
                    {% endif %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ baseUrl }}/admin/tags">
                            <i class="fa fa-tag pr-1"></i>
                            Tags</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ baseUrl }}/admin/indexLogs">
                            <i class="fa fa-info-circle pr-1"></i>
                            Index Logs</a>
                    </li>
                </ul>
            </div>

            <div class="col-lg-10">
                {% block admin_content %}{% endblock %}
            </div>
        </div>
    </div>
{% endblock %}

src/templates/administration/collEdit.html.twig
<div class="modal fade" id="modal-div" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Edit collection</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form id="passwordForm">
          <input name="itemID" type="hidden" value="{{ collId }}">
          <div class="form-group" id="admin_pwd_group">
            <label for="admin_pwd">Administrator Password</label>
            <input id="admin_pwd" name="admin_pwd" class="form-control" type="password" required>
            <div class="invalid-feedback">
              Please provide the correct administrator password.
            </div>
          </div>
          <!-- new column -->

        </form>
      </div>
      <div class="modal-footer">
        <button id="saveButton" type="submit" class="btn btn-outline-primary">
          <i class="fas fa-save"></i>
          Save</button>
      </div>
    </div>
  </div>
</div>

src/templates/administration/indexLogs.html.twig
{% extends 'administration/admin.html.twig' %}

{% block admin_content %}
    <div class="card mb-3" id="indexLogsList">
        <div class="card-body scrollable">
            <table id="indexLogsTable" class="table table-sm table-hover">
                <thead class="table-borderless">
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Recording</th>
                    <th scope="col">Creation User</th>
                    <th scope="col">Index</th>
                    <th scope="col">Coordinates</th>
                    <th scope="col">Parameter</th>
                    <th scope="col">Result</th>
                    <th scope="col">Creation Date (UTC)</th>
                </tr>
                </thead>
                <tbody class="form-control-sm js-user-list">
                {% for indexLog in indexLogs %}
                    <tr>
                        <td scope='row'>{{ indexLog.logId }}</td>
                        <td>{{ indexLog.recordingName }}</td>
                        <td>{{ indexLog.userName }}</td>
                        <td>{{ indexLog.indexName }}</td>
                        <td>{{ indexLog.coordinates }}</td>
                        <td>{{ indexLog.param|replace({'?':': ','@':'; '}) }}</td>
                        <td>{% for v in indexLog.value|split('!') %}{{ v|split('?')[0] }}: {{ v|split('?')[1]|number_format(2,'.',',') }}; {% endfor %}</td>
                        <td>{{ indexLog.date }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="row">
            <div class="col-md-12">
                <nav aria-label="pagination">
                    <ul class="pagination justify-content-center mt-3">
                        {% if pages > 10 %}
                            <li class="page-item">
                                <a href="{{ baseUrl }}/admin/indexLogs/{{ currentPage == 1 ? 1 : currentPage - 1 }}">
                                    <i class="fa fa-angle-left" style="font-size:36px; position:relative; top:4px;"></i>
                                </a>&nbsp;&nbsp;
                            </li>
                            <li class="page-item {{ currentPage == 1 ? 'active' }}">
                                <a class="page-link" href="{{ baseUrl }}/admin/indexLogs/1">1</a>
                            </li>
                            {% if currentPage <= 3 %}
                                <li class="page-item  {{ currentPage == 2 ? 'active' }}">
                                    <a class="page-link" href="{{ baseUrl }}/admin/indexLogs/2">2</a>
                                </li>
                                <li class="page-item {{ currentPage == 3 ? 'active' }}">
                                    <a class="page-link" href="{{ baseUrl }}/admin/indexLogs/3">3</a>
                                </li>
                                <li class="disabled">
                                    <span style="font-size:28px;position:relative;">&nbsp;.</span>
                                    <span style="font-size:28px;position:relative;">.</span>
                                    <span style="font-size:28px;position:relative;">.&nbsp;</span>
                                </li>
                            {% endif %}

                            {% if currentPage >= 4 and currentPage <= (pages - 3) %}
                                <li class="disabled">
                                    <span style="font-size:28px;position:relative;">&nbsp;.</span>
                                    <span style="font-size:28px;position:relative;">.</span>
                                    <span style="font-size:28px;position:relative;">.&nbsp;</span>
                                </li>
                                {% if currentPage == 4 %}
                                    <li class="page-item  active">
                                        <a class="page-link" href="{{ baseUrl }}/admin/indexLogs/4">4</a>
                                    </li>
                                    <li class="page-item">
                                        <a class="page-link"
                                           href="{{ baseUrl }}/admin/indexLogs/{{ currentPage + 1 }}">{{ currentPage + 1 }}</a>
                                    </li>
                                    <li class="page-item">
                                        <a class="page-link"
                                           href="{{ baseUrl }}/admin/indexLogs/{{ currentPage + 2 }}">{{ currentPage + 2 }}</a>
                                    </li>
                                {% elseif currentPage == pages - 3 %}
                                    <li class="page-item">
                                        <a class="page-link"
                                           href="{{ baseUrl }}/admin/indexLogs/{{ currentPage - 2 }}">{{ currentPage - 2 }}</a>
                                    </li>
                                    <li class="page-item">
                                        <a class="page-link"
                                           href="{{ baseUrl }}/admin/indexLogs/{{ currentPage - 1 }}">{{ currentPage - 1 }}</a>
                                    </li>
                                    <li class="page-item active">
                                        <a class="page-link"
                                           href="{{ baseUrl }}/admin/indexLogs/{{ currentPage }}">{{ currentPage }}</a>
                                    </li>
                                {% else %}
                                    <li class="page-item">
                                        <a class="page-link"
                                           href="{{ baseUrl }}/admin/indexLogs/{{ currentPage -1 }}">{{ currentPage - 1 }}</a>
                                    </li>
                                    <li class="page-item active">
                                        <a class="page-link"
                                           href="{{ baseUrl }}/admin/indexLogs/{{ currentPage }}">{{ currentPage }}</a>
                                    </li>
                                    <li class="page-item">
                                        <a class="page-link"
                                           href="{{ baseUrl }}/admin/indexLogs/{{ currentPage + 1 }}">{{ currentPage + 1 }}</a>
                                    </li>
                                {% endif %}
                                <li class="disabled">
                                    <span style="font-size:28px;position:relative;">&nbsp;.</span>
                                    <span style="font-size:28px;position:relative;">.</span>
                                    <span style="font-size:28px;position:relative;">.&nbsp;</span>
                                </li>
                            {% endif %}

                            {% if currentPage >= pages - 2 %}
                                <li class="disabled">
                                    <span style="font-size:28px;position:relative;">&nbsp;.</span>
                                    <span style="font-size:28px;position:relative;">.</span>
                                    <span style="font-size:28px;position:relative;">.&nbsp;</span>
                                </li>
                                <li class="page-item  {{ currentPage == pages - 2 ? 'active' }}">
                                    <a class="page-link"
                                       href="{{ baseUrl }}/admin/indexLogs/{{ pages - 2 }}">{{ pages - 2 }}</a>
                                </li>
                                <li class="page-item {{ currentPage == pages - 1 ? 'active' }}">
                                    <a class="page-link"
                                       href="{{ baseUrl }}/admin/indexLogs/{{ pages - 1 }}">{{ pages -1 }}</a>
                                </li>
                            {% endif %}
                            <li class="page-item {{ currentPage == pages ? 'active' }}">
                                <a class="page-link" href="{{ baseUrl }}/admin/indexLogs/{{ pages }}">{{ pages }}</a>
                            </li>
                            <li class="page-item">&nbsp;&nbsp;
                                <a href="{{ baseUrl }}/admin/indexLogs/{{ currentPage == pages ? pages : currentPage + 1 }}">
                                    <i class="fa fa-angle-right"
                                       style="font-size:36px; position:relative; top:4px;"></i>
                                </a>
                            </li>
                        {% else %}
                            {% for page in range(1, pages) %}
                                <li class="page-item {{ currentPage == page ? 'active' }}">
                                    <a class="page-link" href="{{ baseUrl }}/admin/indexLogs/{{ page }}">
                                        {{ page }}
                                    </a>
                                </li>
                            {% endfor %}
                        {% endif %}
                    </ul>
                </nav>
            </div>
        </div>
        <div class="text-right">
            <button id="indexLogsExport" class="btn btn-outline-primary btn-sm mt-2" type="button"
                    data-target="#indexLogsExport" aria-expanded="false" aria-controls="indexLogsExport">
                <i class="fas"></i>
                Index Log Export
            </button>
        </div>
    </div>
{% endblock %}
{% block header %}
    {{ parent() }}
    <script>
        $(function () {
            'use strict';
            $(document).on('click', '#indexLogsExport', function () {
                window.location.href = '{{ baseUrl }}/api/admin/indexLogMgr/export';
            });
        });
    </script>
{% endblock %}