src/src/BioSounds/Entity/Recording.php
<?php

namespace BioSounds\Entity;


class Recording
{
    const TABLE_NAME = 'recording';
    const ID = 'recording_id';
    const COL_ID = 'col_id';
    const SITE_ID = 'site_id';
    const SENSOR_ID = 'sensor_id';
    const SOUND_ID = 'sound_id';
    const DIRECTORY = 'directory';
    const FILE_SIZE = "file_size";
    const NAME = "name";
    const FILENAME = "filename";
    const FILE_DATE = "file_date";
    const FILE_TIME = "file_time";
    const DURATION = "duration";
    const CHANNEL_NUM = "channel_num";
    const SAMPLING_RATE = "sampling_rate";
    const BITRATE = 'bitrate';
    const MD5_HASH = 'md5_hash';
    const DOI = "doi";
    //const LICENSE ="license";
    const LICENSE_ID = "license_id";
    const LICENSE_NAME = "license_name";
    const SITE_NAME = "site_name";
    const USER_ID = 'user_id';
    const LABEL_ID = "label_id";
    const LABEL_NAME = 'label_name';
    /**
     * @var string
     */
    private $site_name;

    /**
     * @var integer
     */
    private $license;

    /**
     * @var string
     */
    private $license_name;

    /**
     * @var string
     */
    private $doi;

    /**
     * @var int
     */
    private $id;

    /**
     * @var string
     */
    private $name;

    /**
     * @var int
     */
    private $collection;

    /**
     * @var int
     */
    private $directory;

    /**
     * @var int
     */
    private $site;

    /**
     * @var int
     */
    private $sensor;

    /**
     * @var int
     */
    private $sound;

    /**
     * @var int
     */
    private $fileSize;

    /**
     * @var string
     */
    private $fileName;

    /**
     * @var string
     */
    private $fileDate;

    /**
     * @var string
     */
    private $fileTime;

    /**
     * @var int
     */
    private $duration;

    /**
     * @var int
     */
    private $channelNum;

    /**
     * @var int
     */
    private $samplingRate;

    /**
     * @var int
     */
    private $bitrate;

    /**
     * TODO: this should be property 'sound', when using an ORM
     * @var Sound
     */
    private $soundData;



    /**
     *
     * @var int
     */
    private $user_id;

    /**
     * @var string
     */
    private $user_full_name;

    /**
     *
     * @var int
     */
    private $labelId;
    /**
     * @var string
     */
    private $labelName;

    /**
     * @return int
     */
    public function getId(): int
    {
        return $this->id;
    }

    /**
     * @param int $id
     * @return Recording
     */
    public function setId(int $id): Recording
    {
        $this->id = $id;
        return $this;
    }

    /**
     * @return string
     */
    public function getName(): string
    {
        return $this->name;
    }

    /**
     * @param string $name
     * @return Recording
     */
    public function setName(string $name): Recording
    {
        $this->name = $name;
        return $this;
    }

    /**
     * @return int
     */
    public function getCollection(): int
    {
        return $this->collection;
    }

    /**
     * @param int $collection
     * @return Recording
     */
    public function setCollection(int $collection): Recording
    {
        $this->collection = $collection;
        return $this;
    }

    /**
     * @return int
     */
    public function getDirectory(): int
    {
        return $this->directory;
    }

    /**
     * @param int $directory
     * @return Recording
     */
    public function setDirectory(int $directory): Recording
    {
        $this->directory = $directory;
        return $this;
    }

    /**
     * @return int|null
     */
    public function getSite(): ?int
    {
        return $this->site;
    }

    /**
     * @param int|null $site
     * @return Recording
     */
    public function setSite(?int $site): Recording
    {
        $this->site = $site;
        return $this;
    }

    /**
     * @return int|null
     */
    public function getSensor(): ?int
    {
        return $this->sensor;
    }

    /**
     * @param int|null $sensor
     * @return Recording
     */
    public function setSensor(?int $sensor): Recording
    {
        $this->sensor = $sensor;
        return $this;
    }

    /**
     * @return int|null
     */
    public function getSound(): ?int
    {
        return $this->sound;
    }

    /**
     * @return int
     */
    public function getUserId(): int
    {
        return $this->user_id;
    }

    /**
     * @param int|null $sound
     * @return Recording
     */
    public function setSound(?int $sound): Recording
    {
        $this->sound = $sound;
        return $this;
    }

    /**
     * @return int
     */
    public function getFileSize(): int
    {
        return $this->fileSize;
    }

    /**
     * @param int $fileSize
     * @return Recording
     */
    public function setFileSize(int $fileSize): Recording
    {
        $this->fileSize = $fileSize;
        return $this;
    }

    /**
     * @return string
     */
    public function getFileName(): string
    {
        return $this->fileName;
    }

    /**
     * @param string $fileName
     * @return Recording
     */
    public function setFileName(string $fileName): Recording
    {
        $this->fileName = $fileName;
        return $this;
    }

    /**
     * @return null|string
     */
    public function getFileDate(): ?string
    {
        return $this->fileDate;
    }

    /**
     * @param null|string $fileDate
     * @return Recording
     */
    public function setFileDate(?string $fileDate): Recording
    {
        $this->fileDate = $fileDate;
        return $this;
    }

    /**
     * @return null|string
     */
    public function getFileTime(): ?string
    {
        return $this->fileTime;
    }

    /**
     * @param null|string $fileTime
     * @return Recording
     */
    public function setFileTime(?string $fileTime): Recording
    {
        $this->fileTime = $fileTime;
        return $this;
    }

    /**
     * @return int
     */
    public function getDuration(): int
    {
        return $this->duration;
    }

    /**
     * @param int $duration
     * @return Recording
     */
    public function setDuration(int $duration): Recording
    {
        $this->duration = $duration;
        return $this;
    }

    /**
     * @return int
     */
    public function getChannelNum(): int
    {
        return $this->channelNum;
    }

    /**
     * @param int $channelNum
     * @return Recording
     */
    public function setChannelNum(int $channelNum): Recording
    {
        $this->channelNum = $channelNum;
        return $this;
    }

    /**
     * @return int
     */
    public function getSamplingRate(): int
    {
        return $this->samplingRate;
    }

    /**
     * @param int $samplingRate
     * @return Recording
     */
    public function setSamplingRate(int $samplingRate): Recording
    {
        $this->samplingRate = $samplingRate;
        return $this;
    }

    /**
     * @return int
     */
    public function getBitrate(): int
    {
        return $this->bitrate;
    }

    /**
     * @param int $bitrate
     * @return Recording
     */
    public function setBitrate(int $bitrate): Recording
    {
        $this->bitrate = $bitrate;
        return $this;
    }

    /**
     * @return Sound|null
     */
    public function getSoundData(): ?Sound
    {
        return $this->soundData;
    }

    /**
     * @param Sound|null $soundData
     * @return Recording
     */
    public function setSoundData(?Sound $soundData): Recording
    {
        $this->soundData = $soundData;
        return $this;
    }

    /**
     * @param string|null $user_full_name
     * @return Recording
     */
    public function setUserFullName(?string $user_full_name): Recording
    {
        $this->user_full_name = $user_full_name;
        return $this;
    }


    /**
     * @return null|string
     */
    public function getUserFullName(): ?string
    {
        return $this->user_full_name;
    }

    /**
     * @param int $user_id
     * @return Recording
     */
    public function setUserId(int $user_id): Recording
    {
        $this->user_id = $user_id;
        return $this;
    }

    /**
     * @return string
     */
    public function getDoi(): ?string
    {
        return $this->doi;
    }

    /**
     * @param string $doi
     * @return Recording
     */
    public function setDoi(?string $doi): Recording
    {
        $this->doi = $doi;
        return $this;
    }

    /**
     * @return null|int
     */
    public function getLicense(): ?int
    {
        return $this->license;
    }

    /**
     * @return string
     */
    public function getLicenseName(): string
    {
        return $this->license_name;
    }



    /**
     * @param null|int $license
     * @return Recording
     */
    public function setLicense(?int $license): Recording
    {
        $this->license = $license;
        return $this;
    }

    /**
     * @param null|string $license_name
     * @return Recording
     */
    public function setLicenseName(?string $license_name): Recording
    {
        $this->license_name = $license_name;
        return $this;
    }


    /**
     * @return null|string
     */
    public function getSiteName(): ?string
    {
        return $this->site_name;
    }


    /**
     * @param null|string $site_name
     * @return Recording
     */
    public function setSiteName(?string $site_name): Recording
    {
        $this->site_name = $site_name;
        return $this;
    }



    /**
     * @return null|int
     */
    public function getLabelId(): ?int
    {
        return $this->labelId;
    }

    /**
     * @param null|int $labelId
     * @return Recording
     */
    public function setLabelId(?int $labelId): Recording
    {
        $this->labelId = $labelId;
        return $this;
    }

    /**
     * @return string
     */
    public function getLabelName(): ?string
    {
        return $this->labelName;
    }

    /**

src/src/BioSounds/Controller/Administration/CollectionController.php
<?php

namespace BioSounds\Controller\Administration;

use BioSounds\Controller\BaseController;
use BioSounds\Entity\Collection;
use BioSounds\Exception\ForbiddenException;
use BioSounds\Provider\CollectionProvider;
use BioSounds\Utils\Auth;

class CollectionController extends BaseController
{
    const SECTION_TITLE = 'Collections';

    /**
     * @return string
     * @throws \Exception
     */
    public function show(int $page = 1)
    {
        if (!Auth::isUserAdmin()) {
            throw new ForbiddenException();
        }

        $collProvider = new CollectionProvider();

        $collNum = $collProvider->countCollections();
        $pages = $collNum > 0 ? ceil($collNum / self::ITEMS_PAGE) : 1;

        return $this->twig->render('administration/collections.html.twig', [
            'collections' => $collProvider->getCollectionPages(
                $this::ITEMS_PAGE,
                $this::ITEMS_PAGE * ($page - 1)
            ),
            // 'collections' => (new (CollectionProvider))->getList("name"),
            'currentPage' => ($page > $pages) ?: $page,
            'pages' => $pages
        ]);
    }


    /**
     * @return false|string
     * @throws \Exception
     */
    public function save()
    {
        $collProvider = new Collection();

        if (!Auth::isUserAdmin()) {
            throw new ForbiddenException();
        }

        $data = [];

        foreach ($_POST as $key => $value) {
            if (strrpos($key, '_')) {
                $type = substr($key, strrpos($key, '_') + 1, strlen($key));
                $key = substr($key, 0, strrpos($key, '_'));
            }
            $data[$key] = filter_var($value, FILTER_SANITIZE_STRING);
        }
        $data['user_id']=$_SESSION['user_id'];
        if (isset($data['collId'])) {
            $collProvider->updateColl($data);
            return json_encode([
                'errorCode' => 0,
                'message' => 'Collection updated successfully.'
            ]);
        } else if ($collProvider->insertColl($data) > 0) {
            return json_encode([
                'errorCode' => 0,
                'message' => 'Collection created successfully.',
            ]);
        }
    }

    /**
     * @return false|string
     * @throws \Exception
     */
    public function editCollection()
    {
        if (!Auth::isUserAdmin()) {
            throw new ForbiddenException();
        }

        $collId = filter_var($_POST['id'], FILTER_SANITIZE_NUMBER_INT);
        return json_encode([
            'errorCode' => 0,
            'data' => $this->twig->render('administration/collEdit.html.twig', [
                'collId' => $collId,
            ]),
        ]);
    }

    /**
     * @throws \Exception
     */
    public function export()
    {
        if (!Auth::isUserAdmin()) {
            throw new ForbiddenException();
        }

        $file_name = "collections.csv";
        $fp = fopen('php://output', 'w');
        header('Content-Type: application/octet-stream;charset=utf-8');
        header('Accept-Ranges:bytes');
        header('Content-Disposition: attachment; filename=' . $file_name);

        $collList = (new CollectionProvider())->getList();

        foreach ($collList as $collItem) {
            $colArray = array($collItem->getId(), $collItem->getName(), $collItem->getAuthor(), $collItem->getDoi(), $collItem->getNote(), $collItem->getProject());
            $colAls[] = $colArray;
        }

        foreach ($colAls as $line) {
            fputcsv($fp, $line);
        }
        fclose($fp);
        exit();
    }
}

src/templates/collection/views/gallery.html.twig
{% block body %}
    <hr>
    <div class='row'>
        {% for item in list %}
            <div class="col-lg-4 sound-list-item">
                <a href="{{ baseUrl }}/recording/show/{{ item.recording.id }}/{{ pageNum }}" title="BioSounds player">
                    <img src="{{ baseUrl }}/{{ item.smallImage }}">
                </a>
                <span>
                    <span style="display:inline;">{{ item.recording.name }}</span>
                    <span style="display:inline; color: dodgerBlue;">&nbsp;&nbsp;{{ item.recording.labelName }}</span>
                </span>
                <span>{{ item.recording.file_date }}</span>
            </div>
        {% endfor %}
    </div>
{% endblock %}

src/templates/collection/views/list.html.twig
<ul class="list-group list-group-flush my-4">

    {% for item in list %}

        <li class="list-group-item">
            <div class="row">
                <div class="col-auto mr-auto">

                    {% if item.recording.soundData is not empty %}
                        <h5>
                            <strong>{{ item.recording.soundData.speciesName }}</strong>
                        </h5>
                        <h6>Type:
                            <small>{{ item.recording.soundData.typeName }}</small>
                        </h6>
                        <h6>Subtype:
                            <small>{{ item.recording.soundData.subtype }}</small>
                        </h6>
                        <h6>Rating:
                            <small>{{ item.recording.soundData.rating }}</small>
                        </h6>
                        <h6>Filename:
                            <small>{{ item.recording.name }}</small>
                        </h6>
                    {% else %}
                        <h5>
                            <strong>{{ item.recording.name }}</strong>
                        </h5>
                    {% endif %}
                    <h6>Date:
                        <small>{{ item.recording.fileDate|date("d/m/Y") }}</small>
                    </h6>
                    <h6>Time:
                        <small>{{ item.recording.fileTime }}</small>
                    </h6>
                    <h6>User:
                        <small>{{ item.recording.getUserFullName }}
                        </small>
                    </h6>
                    <h6>DOI:
                        <small>{{ item.recording.Doi }}
                        </small>
                    </h6>
                    <h6>Site:
                        <small>{{ item.recording.siteName }}
                        </small>
                    </h6>
                    <h6>License:
                        <small>{{ item.recording.licenseName }}</small>
                        {% if item.recording.licenseName == 'CC-BY' %}
                            <a href="https://creativecommons.org/licenses/by/4.0"><img
                                        src="{{ licenseImagesUrl }}/ccby.png" alt="cc by"/></a>
                        {% elseif item.recording.licenseName == 'CC-BY-SA' %}
                            <a href="https://creativecommons.org/licenses/by-sa/4.0"><img
                                        src="{{ licenseImagesUrl }}/ccby-sa.png" alt="cc by-sa"/></a>
                        {% elseif item.recording.licenseName == 'CC-BY-NC' %}
                            <a href="https://creativecommons.org/licenses/by-nc/4.0"><img
                                        src="{{ licenseImagesUrl }}/ccby-nc.png" alt="cc by-nc"/></a>
                        {% elseif item.recording.licenseName == 'CC-BY-NC-SA' %}
                            <a href="https://creativecommons.org/licenses/by-nc-sa/4.0"><img
                                        src="{{ licenseImagesUrl }}/ccby-nc-sa.png" alt="cc by-nc-sa"/></a>
                        {% elseif item.recording.licenseName == 'CC-BY-ND' %}
                            <a href="https://creativecommons.org/licenses/by-nd/4.0"><img
                                        src="{{ licenseImagesUrl }}/ccby-nd.png" alt="cc by-nd"/></a>
                        {% elseif item.recording.licenseName == 'CC-BY-NC-ND' %}
                            <a href="https://creativecommons.org/licenses/by-nc-nd/4.0"><img
                                        src="{{ licenseImagesUrl }}/ccby-nc-nd.png" alt="cc by-nc-nd"/></a>
                        {% endif %}
                    </h6>
                    {% if item.recording.siteData is not empty %}
                        <h6>Site:
                            <small>{{ item.recording.siteData.name }}</small>
                        </h6>
                    {% endif %}
                    {% if item.recording.note is not empty %}
                        <h6>Notes:
                            <small>{{ item.recording.note }}</small>
                        </h6>
                    {% endif %}
                </div>
                <div class="col-3">
                    <h6>&nbsp;</h6>
                    <h6>
                        My Label:<small>
                            {{ item.recording.labelName }}
                        </small>
                    </h6>
                    {% if item.recording.realmName is not empty %}
                        <h6>
                            Realm:<small>
                                {{ item.recording.realmName }}
                            </small>
                        </h6>
                    {% endif %}
                    {% if item.recording.biomeName is not empty %}
                        <h6>
                            Biome:<small>
                                {{ item.recording.biomeName }}
                            </small>
                        </h6>
                    {% endif %}
                    {% if item.recording.FunctionalGroupName is not empty %}
                        <h6>
                            Functional Group:<small>
                                {{ item.recording.FunctionalGroupName }}
                            </small>
                        </h6>
                    {% endif %}
                </div>
                <div class="col-6">
                    <div id="player-cursor" class="small-player-cursor" data-cursor-id="{{ item.recording.id }}"></div>
                    <a href="{{ baseUrl }}/recording/show/{{ item.recording.id }}/{{ pageNum }}" title="BioSounds player">
                        <img class="small-player-image" src="{{ baseUrl }}/{{ item.playerImage }}">
                    </a>
                    <audio id="player" data-id="{{ item.recording.id }}" controls>
                        <source src="{{ baseUrl }}/{{ item.playerRecording }}"/>
                    </audio>
                </div>
            </div>
        </li>
    {% endfor %}
</ul>